remove redundant hardware test
DeepWok/mase pull request #237
Opened 2024-12-27 17:26 UTC by firemountain154B

2024-12-28 02:45 UTC, Aaron-Zhao123 commented
Do you want to pull from main and then merge? I think this error was triggered by something I just fixed.

2024-12-28 21:41 UTC, firemountain154B commented
> Do you want to pull from main and then merge? I think this error was triggered by something I just fixed.

Done!

2024-12-29 17:04 UTC, Aaron-Zhao123 requested changes

2024-12-29 17:04 UTC, Aaron-Zhao123 commented on justfile
@firemountain154B can you leave a comment above on the tests that are disabled because they are time-consuming? or you can maybe do test-hw-slow-mode in the make filee to bundle these tests? The problem with simply commenting them out is they are then mixed with the other commented commands?

2025-02-16 18:58 UTC, merged